App\Entity\Competition:
  attributes:
    id:
      groups: ['competition_read']
    isOpen:
      groups: ['competition_read']
    isFinished:
      groups: ['competition_read']
    name:
      groups: ['competition_read']
    description:
      groups: ['competition_read']
    url:
      groups: ['competition_read']
    heldAt:
      groups: ['competition_read']
    game:
      groups: ['competition_read']