App\Entity\Round:
  attributes:
    id:
      groups: ['round_read']
    competition:
      groups: ['round_read']
    bracketLevel:
      groups: ['round_read']
    bracketOrder:
      groups: ['round_read']
    bestOf:
      groups: ['round_read', 'round_write']
    lobbyName:
      groups: ['round_read', 'round_write']
    lobbyPassword:
      groups: ['round_read', 'round_write']
    winner:
      groups: ['round_read', 'round_write']